### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by eliassjogreen** [tr1ckydev/webview-bun#1]
It seems this is based of my module [webview_deno](https://github.com/webview/webview_deno) without proper attribution and with all references to me or the webview project removed; Something that is in violation of the MIT license.

I suggest that you add proper attribution and do so in any of your future open-source endevours. An important aspect of the open-source community is respecting licenses and giving proper attribution.

I hope this can be resolved quickly and respectfully!

Cheers, Elias from [Denosaurs](https://github.com/denosaurs)

**Comment by tr1ckydev** [comment]
I apologize for forgetting to credit the webview_deno project, off which this port is based.

Proper attribution has now been added in the README.
https://github.com/tr1ckydev/webview-bun#credits

**Comment by eliassjogreen** [comment]
Cool thanks! I would suggest you also add
```
Copyright (c) 2020-2022 the webview team
```
before your copyright line in the LICENSE file.

**Comment by tr1ckydev** [comment]
Yes, added.
