### ISSUE TITLE
Feature request: fullscreen

### ISSUE THREAD

**Issue by MartinGamesCZ** [tr1ckydev/webview-bun#12]
Would it be please possible to implement fullscreen function? Or is there some "hack" to do it? I tried fullscreen using javascript on the page, but that requires user to click, which is not very practical

**Comment by tr1ckydev** [comment]
Even though out of scope of this project but I tried few ways most notably using setTimeout but it requires the user to atleast click inside the window once, else fails with a promise rejection.

**Comment by MartinGamesCZ** [comment]
Thanks, i meanwhile started working on my own rust based implementation with full control

**Comment by tr1ckydev** [comment]
That's wonderful. I wish you all the best for your project.
