### ISSUE TITLE
Tries to load bundled lib file even when `WEBVIEW_PATH` is set. Errors if lib files are excluded from the bundle.

### ISSUE THREAD

**Issue by citkane** [tr1ckydev/webview-bun#14]
I am setting `process.env.WEBVIEW_PATH` to use a custom build lib file and excluding the default libs from my bundle: 
```ts
Bun.build({
    ...,
    external: [<the default ../build/libwebview.whatever files>]
})
``` 

At runtime however, `webview-bun` still [tries to import the default lib file](https://github.com/tr1ckydev/webview-bun/blob/v2.1.0/src/ffi.ts#L21-L34) before [opening the given `WEBVIEW_PATH`](https://github.com/tr1ckydev/webview-bun/blob/v2.1.0/src/ffi.ts#L39). This causes a fatal error.

The fix should be fairly simple, PR #15.

**Comment by tr1ckydev** [comment]
Fixed in latest commit.
