### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Shawak** [tr1ckydev/webview-bun#2]
Are there any plans in supporting windows anytime soon?

Edit: I just realized bun doesn't fully support windows yet, guess we'll have to wait

**Comment by tr1ckydev** [comment]
Yes, it doesn't natively yet but using Deno you can, but through bun WSL is the only way for now.

**Comment by Shawak** [comment]
Related:
https://github.com/oven-sh/bun/issues/43
https://github.com/oven-sh/bun/pull/4410

**Comment by Shawak** [comment]
For now it can be run in WSL2 using `LIBGL_ALWAYS_SOFTWARE=1 bun run .`

**Comment by tr1ckydev** [comment]
Added support in v2.0.0.
