### ISSUE TITLE
Windows feature support

### ISSUE THREAD

**Issue by kamenomi-dev** [tr1ckydev/webview-bun#23]
Hello developer👋
For Windows platform, we need support for window icons instead of the default "small window",
Do we have plans to achieve this?

**Comment by tr1ckydev** [comment]
Although there are no plans to support it right now, please take a look [here](https://github.com/webview/webview/issues/781).

**Comment by kamenomi-dev** [comment]
I see, it needs me to compile a new webview library to achieve it. Thanks!
