### ISSUE TITLE
(windows): ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by hjbdev** [tr1ckydev/webview-bun#5]
```
 src-backend  bun .\index.js
23 |     case "linux": lib_path += "libwebview.so"; break;
24 |     case "darwin": lib_path += `libwebview.${process.arch}.dylib`; break;
25 |     default: throw "unsupported platform: " + process.platform;
26 | }
27 |
28 | export const lib = dlopen(process.env.WEBVIEW_PATH ?? lib_path, {
                        ^
ERR_DLOPEN_FAILED: Failed to open library. This is usually caused by a missing library or an invalid library path.
 syscall: "dlopen"

      at bun:ffi:61:41
      at C:\Users\Harry\Dev\broadcast-kit-next\node_modules\webview-bun\src\ffi.ts:28:20
```

`index.js` just contains the [basic example](https://github.com/tr1ckydev/webview-bun/blob/main/examples/basic.ts)

I added a console.log to the `lib_path` variable in `ffi.ts` and it's pointing to the correct dll, so might be an issue with bun itself? I'm on bun 1.1.3.

**Comment by tr1ckydev** [comment]
It's not a issue with bun, but something i still haven't found yet. I do have a workout which is to clone repo and built the dll atleast once on the host system, but why does it work, I've yet to find out.

**Comment by tr1ckydev** [comment]
Fixed in latest commit.

**Comment by MikeyA-yo** [comment]
> Fixed in latest commit.
but i still get that error when using it on windows
