### ISSUE TITLE
Add webview options

### ISSUE THREAD

**Issue by fckffln** [tr1ckydev/webview-bun#7]
Please add options for webview, the same as in electron

Example list of options:
https://www.electronjs.org/docs/latest/api/browser-window

**Comment by tr1ckydev** [comment]
Windows height and width can be changed when creating an instance. Refer to https://github.com/tr1ckydev/webview-bun/blob/main/src/webview.ts#L141

**Comment by merlindru** [comment]
What about other options? E.g. hiding window decorations/title bar, making the window transparent/blurry/acrylic/mica

**Comment by tr1ckydev** [comment]
> What about other options? E.g. hiding window decorations/title bar, making the window transparent/blurry/acrylic/mica

Unfortunately, these are out of the scope of this project as those depend on the webview project decisions with what API they chose to implement.
